testB = true
testI = -42
testF = 1.23
testS = "foobar"
testA = [   "abacaba", "foo", 'bar'    ]
testN = "newtype"
# testStatus = "username"

testC = "Light"
# testC = "Dark"
# testC = "HighContrast"

# either.Left = 3
either.Right = "Right"

either = 3.5
# Also works!
# either = "fo  o"

payloads =
    [ { name = "foo", payload = 42 }
    , { name = "bar", payload = 69 }
    ]

[testX]
  inside = "xxx"

# [testY]
#   inside = "yyy"

[[user]]
name = "Foo"
age = 42

[[user]]
name = "Bar"
age = 777

[testStatus]
username = "username"
password = "password"

[dependencies]
thing1 = "simple"
thing2 = { git = "somewhere" }
thing3 = { git = "else", version = "1.0" }
thing4 = { path = "here" }
thing5 = { path = "there", version = "1.1" }
